<?php require_once INCLUDE_DIR."personality.php"; $GLOBALS["personalities"]=unserialize(<<<EOD
a:11:{i:1;O:11:"PERSONALITY":25:{s:4:"name";s:4:"Rolf";s:14:"base_animation";s:14:"base_animation";s:9:"base_data";a:3:{s:6:"images";a:1:{i:0;s:8:"rolf.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:15:"equip_animation";s:14:"pose_animation";s:10:"equip_data";a:3:{s:6:"images";a:1:{i:0;s:8:"rolf.png";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"flee_animation";s:14:"flee_animation";s:9:"flee_data";a:3:{s:6:"images";a:1:{i:0;s:8:"rolf.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:13:"hit_animation";s:14:"pose_animation";s:8:"hit_data";a:3:{s:6:"images";a:1:{i:0;s:8:"rolf.png";}s:6:"sounds";a:1:{i:0;s:10:"Earth3.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:13:"die_animation";s:13:"die_animation";s:8:"die_data";a:3:{s:6:"images";a:1:{i:0;s:8:"rolf.png";}s:6:"sounds";a:2:{i:0;s:10:"Earth3.mp3";i:1;s:7:"die.mp3";}s:5:"times";a:3:{i:0;s:3:"500";i:1;s:2:"10";i:2;s:1:"5";}}s:22:"attack_close_animation";s:22:"attack_close_animation";s:17:"attack_close_data";a:3:{s:6:"images";a:3:{i:0;s:8:"rolf.png";i:1;s:15:"rolf_attack.gif";i:2;s:8:"rolf.png";}s:6:"sounds";a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}s:5:"times";a:3:{i:0;s:2:"25";i:1;s:3:"500";i:2;s:3:"500";}}s:22:"attack_throw_animation";s:14:"pose_animation";s:17:"attack_throw_data";a:3:{s:6:"images";a:1:{i:0;s:15:"rolf_attack.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"attack_shoot_animation";s:14:"pose_animation";s:17:"attack_shoot_data";a:3:{s:6:"images";a:1:{i:0;s:15:"rolf_attack.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"skill_animation";s:14:"pose_animation";s:10:"skill_data";a:3:{s:6:"images";a:1:{i:0;s:13:"rolf_cast.gif";}s:6:"sounds";a:1:{i:0;s:9:"skill.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"spell_animation";s:14:"pose_animation";s:10:"spell_data";a:3:{s:6:"images";a:1:{i:0;s:13:"rolf_cast.gif";}s:6:"sounds";a:1:{i:0;s:10:"cast_2.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"item_animation";s:14:"pose_animation";s:9:"item_data";a:3:{s:6:"images";a:1:{i:0;s:13:"rolf_cast.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"overworld_stand_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}s:21:"overworld_move_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}}i:2;O:11:"PERSONALITY":25:{s:4:"name";s:3:"Nei";s:14:"base_animation";s:14:"base_animation";s:9:"base_data";a:3:{s:6:"images";a:1:{i:0;s:7:"nei.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:15:"equip_animation";s:14:"pose_animation";s:10:"equip_data";a:3:{s:6:"images";a:1:{i:0;s:7:"nei.png";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"flee_animation";s:14:"flee_animation";s:9:"flee_data";a:3:{s:6:"images";a:1:{i:0;s:7:"nei.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:13:"hit_animation";s:14:"pose_animation";s:8:"hit_data";a:3:{s:6:"images";a:1:{i:0;s:7:"nei.png";}s:6:"sounds";a:1:{i:0;s:10:"Earth3.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:13:"die_animation";s:13:"die_animation";s:8:"die_data";a:3:{s:6:"images";a:1:{i:0;s:7:"nei.png";}s:6:"sounds";a:2:{i:0;s:10:"Earth3.mp3";i:1;s:7:"die.mp3";}s:5:"times";a:3:{i:0;s:3:"500";i:1;s:2:"10";i:2;s:1:"5";}}s:22:"attack_close_animation";s:22:"attack_close_animation";s:17:"attack_close_data";a:3:{s:6:"images";a:3:{i:0;s:7:"nei.png";i:1;s:14:"nei_attack.gif";i:2;s:7:"nei.png";}s:6:"sounds";a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}s:5:"times";a:3:{i:0;s:2:"25";i:1;s:3:"500";i:2;s:3:"500";}}s:22:"attack_throw_animation";s:14:"pose_animation";s:17:"attack_throw_data";a:3:{s:6:"images";a:1:{i:0;s:14:"nei_attack.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"attack_shoot_animation";s:14:"pose_animation";s:17:"attack_shoot_data";a:3:{s:6:"images";a:1:{i:0;s:14:"nei_attack.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"skill_animation";s:14:"pose_animation";s:10:"skill_data";a:3:{s:6:"images";a:1:{i:0;s:12:"nei_cast.gif";}s:6:"sounds";a:1:{i:0;s:9:"skill.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"spell_animation";s:14:"pose_animation";s:10:"spell_data";a:3:{s:6:"images";a:1:{i:0;s:12:"nei_cast.gif";}s:6:"sounds";a:1:{i:0;s:10:"cast_2.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"item_animation";s:14:"pose_animation";s:9:"item_data";a:3:{s:6:"images";a:1:{i:0;s:12:"nei_cast.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"overworld_stand_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}s:21:"overworld_move_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}}i:3;O:11:"PERSONALITY":25:{s:4:"name";s:4:"Alys";s:14:"base_animation";s:14:"base_animation";s:9:"base_data";a:3:{s:6:"images";a:1:{i:0;s:8:"alys.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:15:"equip_animation";s:14:"pose_animation";s:10:"equip_data";a:3:{s:6:"images";a:1:{i:0;s:8:"alys.png";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"flee_animation";s:14:"flee_animation";s:9:"flee_data";a:3:{s:6:"images";a:1:{i:0;s:8:"alys.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:13:"hit_animation";s:14:"pose_animation";s:8:"hit_data";a:3:{s:6:"images";a:1:{i:0;s:8:"alys.png";}s:6:"sounds";a:1:{i:0;s:10:"Earth3.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:13:"die_animation";s:13:"die_animation";s:8:"die_data";a:3:{s:6:"images";a:1:{i:0;s:8:"alys.png";}s:6:"sounds";a:2:{i:0;s:10:"Earth3.mp3";i:1;s:7:"die.mp3";}s:5:"times";a:3:{i:0;s:3:"500";i:1;s:2:"10";i:2;s:1:"5";}}s:22:"attack_close_animation";s:22:"attack_close_animation";s:17:"attack_close_data";a:3:{s:6:"images";a:3:{i:0;s:8:"alys.png";i:1;s:15:"alys_attack.gif";i:2;s:8:"alys.png";}s:6:"sounds";a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}s:5:"times";a:3:{i:0;s:2:"25";i:1;s:3:"500";i:2;s:3:"500";}}s:22:"attack_throw_animation";s:14:"pose_animation";s:17:"attack_throw_data";a:3:{s:6:"images";a:1:{i:0;s:15:"alys_attack.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"attack_shoot_animation";s:14:"pose_animation";s:17:"attack_shoot_data";a:3:{s:6:"images";a:1:{i:0;s:15:"alys_attack.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"skill_animation";s:14:"pose_animation";s:10:"skill_data";a:3:{s:6:"images";a:1:{i:0;s:13:"alys_cast.gif";}s:6:"sounds";a:1:{i:0;s:9:"skill.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"spell_animation";s:14:"pose_animation";s:10:"spell_data";a:3:{s:6:"images";a:1:{i:0;s:13:"alys_cast.gif";}s:6:"sounds";a:1:{i:0;s:10:"cast_2.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"item_animation";s:14:"pose_animation";s:9:"item_data";a:3:{s:6:"images";a:1:{i:0;s:13:"alys_cast.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"overworld_stand_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}s:21:"overworld_move_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}}i:4;O:11:"PERSONALITY":25:{s:4:"name";s:4:"Chaz";s:14:"base_animation";s:14:"base_animation";s:9:"base_data";a:3:{s:6:"images";a:1:{i:0;s:8:"chaz.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:15:"equip_animation";s:14:"pose_animation";s:10:"equip_data";a:3:{s:6:"images";a:1:{i:0;s:8:"chaz.png";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"flee_animation";s:14:"flee_animation";s:9:"flee_data";a:3:{s:6:"images";a:1:{i:0;s:8:"chaz.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:13:"hit_animation";s:14:"pose_animation";s:8:"hit_data";a:3:{s:6:"images";a:1:{i:0;s:8:"chaz.png";}s:6:"sounds";a:1:{i:0;s:10:"Earth3.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:13:"die_animation";s:13:"die_animation";s:8:"die_data";a:3:{s:6:"images";a:1:{i:0;s:8:"chaz.png";}s:6:"sounds";a:2:{i:0;s:10:"Earth3.mp3";i:1;s:7:"die.mp3";}s:5:"times";a:3:{i:0;s:3:"500";i:1;s:2:"10";i:2;s:1:"5";}}s:22:"attack_close_animation";s:22:"attack_close_animation";s:17:"attack_close_data";a:3:{s:6:"images";a:3:{i:0;s:8:"chaz.png";i:1;s:15:"chaz_attack.gif";i:2;s:8:"chaz.png";}s:6:"sounds";a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}s:5:"times";a:3:{i:0;s:2:"25";i:1;s:3:"500";i:2;s:3:"500";}}s:22:"attack_throw_animation";s:14:"pose_animation";s:17:"attack_throw_data";a:3:{s:6:"images";a:1:{i:0;s:15:"chaz_attack.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"attack_shoot_animation";s:14:"pose_animation";s:17:"attack_shoot_data";a:3:{s:6:"images";a:1:{i:0;s:15:"chaz_attack.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"skill_animation";s:14:"pose_animation";s:10:"skill_data";a:3:{s:6:"images";a:1:{i:0;s:13:"chaz_cast.gif";}s:6:"sounds";a:1:{i:0;s:9:"skill.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"spell_animation";s:14:"pose_animation";s:10:"spell_data";a:3:{s:6:"images";a:1:{i:0;s:13:"chaz_cast.gif";}s:6:"sounds";a:1:{i:0;s:10:"cast_2.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"item_animation";s:14:"pose_animation";s:9:"item_data";a:3:{s:6:"images";a:1:{i:0;s:13:"chaz_cast.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"overworld_stand_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}s:21:"overworld_move_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}}i:1000;O:11:"PERSONALITY":25:{s:4:"name";s:5:"Troll";s:14:"base_animation";s:14:"base_animation";s:9:"base_data";a:3:{s:6:"images";a:1:{i:0;s:11:"woodman.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:15:"equip_animation";s:14:"pose_animation";s:10:"equip_data";a:3:{s:6:"images";a:1:{i:0;s:11:"woodman.png";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"flee_animation";s:14:"flee_animation";s:9:"flee_data";a:3:{s:6:"images";a:1:{i:0;s:11:"woodman.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:13:"hit_animation";s:14:"pose_animation";s:8:"hit_data";a:3:{s:6:"images";a:1:{i:0;s:11:"woodman.png";}s:6:"sounds";a:1:{i:0;s:10:"Earth3.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:13:"die_animation";s:13:"die_animation";s:8:"die_data";a:3:{s:6:"images";a:1:{i:0;s:11:"woodman.png";}s:6:"sounds";a:2:{i:0;s:10:"Earth3.mp3";i:1;s:7:"die.mp3";}s:5:"times";a:3:{i:0;s:3:"500";i:1;s:2:"10";i:2;s:1:"5";}}s:22:"attack_close_animation";s:22:"attack_close_animation";s:17:"attack_close_data";a:3:{s:6:"images";a:3:{i:0;s:11:"woodman.png";i:1;s:11:"woodman.gif";i:2;s:11:"woodman.png";}s:6:"sounds";a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}s:5:"times";a:3:{i:0;s:2:"25";i:1;s:3:"500";i:2;s:3:"500";}}s:22:"attack_throw_animation";s:14:"pose_animation";s:17:"attack_throw_data";a:3:{s:6:"images";a:1:{i:0;s:11:"woodman.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"attack_shoot_animation";s:14:"pose_animation";s:17:"attack_shoot_data";a:3:{s:6:"images";a:1:{i:0;s:11:"woodman.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"skill_animation";s:14:"pose_animation";s:10:"skill_data";a:3:{s:6:"images";a:1:{i:0;s:11:"woodman.gif";}s:6:"sounds";a:1:{i:0;s:9:"skill.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"spell_animation";s:14:"pose_animation";s:10:"spell_data";a:3:{s:6:"images";a:1:{i:0;s:11:"woodman.gif";}s:6:"sounds";a:1:{i:0;s:10:"cast_2.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"item_animation";s:14:"pose_animation";s:9:"item_data";a:3:{s:6:"images";a:1:{i:0;s:11:"woodman.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"overworld_stand_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}s:21:"overworld_move_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}}i:1001;O:11:"PERSONALITY":25:{s:4:"name";s:6:"Goblin";s:14:"base_animation";s:14:"base_animation";s:9:"base_data";a:3:{s:6:"images";a:1:{i:0;s:10:"goblin.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:15:"equip_animation";s:14:"pose_animation";s:10:"equip_data";a:3:{s:6:"images";a:1:{i:0;s:10:"goblin.png";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"flee_animation";s:14:"flee_animation";s:9:"flee_data";a:3:{s:6:"images";a:1:{i:0;s:10:"goblin.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:13:"hit_animation";s:14:"pose_animation";s:8:"hit_data";a:3:{s:6:"images";a:1:{i:0;s:10:"goblin.png";}s:6:"sounds";a:1:{i:0;s:10:"Earth3.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:13:"die_animation";s:13:"die_animation";s:8:"die_data";a:3:{s:6:"images";a:1:{i:0;s:10:"goblin.png";}s:6:"sounds";a:2:{i:0;s:10:"Earth3.mp3";i:1;s:7:"die.mp3";}s:5:"times";a:3:{i:0;s:3:"500";i:1;s:2:"10";i:2;s:1:"5";}}s:22:"attack_close_animation";s:22:"attack_close_animation";s:17:"attack_close_data";a:3:{s:6:"images";a:3:{i:0;s:10:"goblin.png";i:1;s:10:"goblin.gif";i:2;s:10:"goblin.png";}s:6:"sounds";a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}s:5:"times";a:3:{i:0;s:2:"25";i:1;s:3:"500";i:2;s:3:"500";}}s:22:"attack_throw_animation";s:14:"pose_animation";s:17:"attack_throw_data";a:3:{s:6:"images";a:1:{i:0;s:10:"goblin.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"attack_shoot_animation";s:14:"pose_animation";s:17:"attack_shoot_data";a:3:{s:6:"images";a:1:{i:0;s:10:"goblin.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"skill_animation";s:14:"pose_animation";s:10:"skill_data";a:3:{s:6:"images";a:1:{i:0;s:10:"goblin.gif";}s:6:"sounds";a:1:{i:0;s:9:"skill.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"spell_animation";s:14:"pose_animation";s:10:"spell_data";a:3:{s:6:"images";a:1:{i:0;s:10:"goblin.gif";}s:6:"sounds";a:1:{i:0;s:10:"cast_2.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"item_animation";s:14:"pose_animation";s:9:"item_data";a:3:{s:6:"images";a:1:{i:0;s:10:"goblin.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"overworld_stand_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}s:21:"overworld_move_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}}i:1002;O:11:"PERSONALITY":25:{s:4:"name";s:7:"Gremlin";s:14:"base_animation";s:14:"base_animation";s:9:"base_data";a:3:{s:6:"images";a:1:{i:0;s:11:"gremlin.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:15:"equip_animation";s:14:"pose_animation";s:10:"equip_data";a:3:{s:6:"images";a:1:{i:0;s:11:"gremlin.png";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"flee_animation";s:14:"flee_animation";s:9:"flee_data";a:3:{s:6:"images";a:1:{i:0;s:11:"gremlin.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:13:"hit_animation";s:14:"pose_animation";s:8:"hit_data";a:3:{s:6:"images";a:1:{i:0;s:11:"gremlin.png";}s:6:"sounds";a:1:{i:0;s:10:"Earth3.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:13:"die_animation";s:13:"die_animation";s:8:"die_data";a:3:{s:6:"images";a:1:{i:0;s:11:"gremlin.png";}s:6:"sounds";a:2:{i:0;s:10:"Earth3.mp3";i:1;s:7:"die.mp3";}s:5:"times";a:3:{i:0;s:3:"500";i:1;s:2:"10";i:2;s:1:"5";}}s:22:"attack_close_animation";s:22:"attack_close_animation";s:17:"attack_close_data";a:3:{s:6:"images";a:3:{i:0;s:11:"gremlin.png";i:1;s:11:"gremlin.gif";i:2;s:11:"gremlin.png";}s:6:"sounds";a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}s:5:"times";a:3:{i:0;s:2:"25";i:1;s:3:"500";i:2;s:3:"500";}}s:22:"attack_throw_animation";s:14:"pose_animation";s:17:"attack_throw_data";a:3:{s:6:"images";a:1:{i:0;s:11:"gremlin.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"attack_shoot_animation";s:14:"pose_animation";s:17:"attack_shoot_data";a:3:{s:6:"images";a:1:{i:0;s:11:"gremlin.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"skill_animation";s:14:"pose_animation";s:10:"skill_data";a:3:{s:6:"images";a:1:{i:0;s:11:"gremlin.gif";}s:6:"sounds";a:1:{i:0;s:9:"skill.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"spell_animation";s:14:"pose_animation";s:10:"spell_data";a:3:{s:6:"images";a:1:{i:0;s:11:"gremlin.gif";}s:6:"sounds";a:1:{i:0;s:10:"cast_2.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"item_animation";s:14:"pose_animation";s:9:"item_data";a:3:{s:6:"images";a:1:{i:0;s:11:"gremlin.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"overworld_stand_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}s:21:"overworld_move_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}}i:1003;O:11:"PERSONALITY":25:{s:4:"name";s:5:"Hippo";s:14:"base_animation";s:14:"base_animation";s:9:"base_data";a:3:{s:6:"images";a:1:{i:0;s:16:"hungry_hippo.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:15:"equip_animation";s:14:"pose_animation";s:10:"equip_data";a:3:{s:6:"images";a:1:{i:0;s:16:"hungry_hippo.png";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"flee_animation";s:14:"flee_animation";s:9:"flee_data";a:3:{s:6:"images";a:1:{i:0;s:16:"hungry_hippo.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:13:"hit_animation";s:14:"pose_animation";s:8:"hit_data";a:3:{s:6:"images";a:1:{i:0;s:16:"hungry_hippo.png";}s:6:"sounds";a:1:{i:0;s:10:"Earth3.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:13:"die_animation";s:13:"die_animation";s:8:"die_data";a:3:{s:6:"images";a:1:{i:0;s:16:"hungry_hippo.png";}s:6:"sounds";a:2:{i:0;s:10:"Earth3.mp3";i:1;s:7:"die.mp3";}s:5:"times";a:3:{i:0;s:3:"500";i:1;s:2:"10";i:2;s:1:"5";}}s:22:"attack_close_animation";s:22:"attack_close_animation";s:17:"attack_close_data";a:3:{s:6:"images";a:3:{i:0;s:16:"hungry_hippo.png";i:1;s:16:"hungry_hippo.gif";i:2;s:16:"hungry_hippo.png";}s:6:"sounds";a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}s:5:"times";a:3:{i:0;s:2:"25";i:1;s:3:"500";i:2;s:3:"500";}}s:22:"attack_throw_animation";s:14:"pose_animation";s:17:"attack_throw_data";a:3:{s:6:"images";a:1:{i:0;s:16:"hungry_hippo.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"attack_shoot_animation";s:14:"pose_animation";s:17:"attack_shoot_data";a:3:{s:6:"images";a:1:{i:0;s:16:"hungry_hippo.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"skill_animation";s:14:"pose_animation";s:10:"skill_data";a:3:{s:6:"images";a:1:{i:0;s:16:"hungry_hippo.gif";}s:6:"sounds";a:1:{i:0;s:9:"skill.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"spell_animation";s:14:"pose_animation";s:10:"spell_data";a:3:{s:6:"images";a:1:{i:0;s:16:"hungry_hippo.gif";}s:6:"sounds";a:1:{i:0;s:10:"cast_2.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"item_animation";s:14:"pose_animation";s:9:"item_data";a:3:{s:6:"images";a:1:{i:0;s:16:"hungry_hippo.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"overworld_stand_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}s:21:"overworld_move_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}}i:1004;O:11:"PERSONALITY":25:{s:4:"name";s:6:"Jordie";s:14:"base_animation";s:14:"base_animation";s:9:"base_data";a:3:{s:6:"images";a:1:{i:0;s:10:"jordie.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:15:"equip_animation";s:14:"pose_animation";s:10:"equip_data";a:3:{s:6:"images";a:1:{i:0;s:10:"jordie.png";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"flee_animation";s:14:"flee_animation";s:9:"flee_data";a:3:{s:6:"images";a:1:{i:0;s:10:"jordie.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:13:"hit_animation";s:14:"pose_animation";s:8:"hit_data";a:3:{s:6:"images";a:1:{i:0;s:10:"jordie.png";}s:6:"sounds";a:1:{i:0;s:17:"jordie_squeak.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:13:"die_animation";s:13:"die_animation";s:8:"die_data";a:3:{s:6:"images";a:1:{i:0;s:14:"jordie_die.gif";}s:6:"sounds";a:2:{i:0;s:10:"Earth3.mp3";i:1;s:17:"jordie_shreak.mp3";}s:5:"times";a:3:{i:0;s:3:"700";i:1;s:3:"500";i:2;s:1:"5";}}s:22:"attack_close_animation";s:22:"attack_close_animation";s:17:"attack_close_data";a:3:{s:6:"images";a:3:{i:0;s:10:"jordie.png";i:1;s:14:"jordie_ani.gif";i:2;s:10:"jordie.png";}s:6:"sounds";a:3:{i:0;s:0:"";i:1;s:14:"jordie_hey.mp3";i:2;s:0:"";}s:5:"times";a:3:{i:0;s:2:"25";i:1;s:3:"500";i:2;s:3:"500";}}s:22:"attack_throw_animation";s:14:"pose_animation";s:17:"attack_throw_data";a:3:{s:6:"images";a:1:{i:0;s:14:"jordie_ani.gif";}s:6:"sounds";a:1:{i:0;s:14:"jordie_hey.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"attack_shoot_animation";s:14:"pose_animation";s:17:"attack_shoot_data";a:3:{s:6:"images";a:1:{i:0;s:14:"jordie_ani.gif";}s:6:"sounds";a:1:{i:0;s:14:"jordie_hey.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"skill_animation";s:14:"pose_animation";s:10:"skill_data";a:3:{s:6:"images";a:1:{i:0;s:10:"jordie.png";}s:6:"sounds";a:1:{i:0;s:9:"skill.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"spell_animation";s:14:"pose_animation";s:10:"spell_data";a:3:{s:6:"images";a:1:{i:0;s:10:"jordie.png";}s:6:"sounds";a:1:{i:0;s:10:"cast_2.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"item_animation";s:14:"pose_animation";s:9:"item_data";a:3:{s:6:"images";a:1:{i:0;s:10:"jordie.png";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"overworld_stand_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}s:21:"overworld_move_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}}i:1005;O:11:"PERSONALITY":25:{s:4:"name";s:6:"Q Bird";s:14:"base_animation";s:14:"base_animation";s:9:"base_data";a:3:{s:6:"images";a:1:{i:0;s:9:"qbird.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:15:"equip_animation";s:14:"pose_animation";s:10:"equip_data";a:3:{s:6:"images";a:1:{i:0;s:9:"qbird.png";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"flee_animation";s:14:"flee_animation";s:9:"flee_data";a:3:{s:6:"images";a:1:{i:0;s:9:"qbird.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:13:"hit_animation";s:14:"pose_animation";s:8:"hit_data";a:3:{s:6:"images";a:1:{i:0;s:9:"qbird.png";}s:6:"sounds";a:1:{i:0;s:10:"Earth3.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:13:"die_animation";s:13:"die_animation";s:8:"die_data";a:3:{s:6:"images";a:1:{i:0;s:9:"qbird.png";}s:6:"sounds";a:2:{i:0;s:10:"Earth3.mp3";i:1;s:7:"die.mp3";}s:5:"times";a:3:{i:0;s:3:"500";i:1;s:2:"10";i:2;s:1:"5";}}s:22:"attack_close_animation";s:22:"attack_close_animation";s:17:"attack_close_data";a:3:{s:6:"images";a:3:{i:0;s:9:"qbird.png";i:1;s:14:"qbird_head.gif";i:2;s:9:"qbird.png";}s:6:"sounds";a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}s:5:"times";a:3:{i:0;s:2:"25";i:1;s:3:"500";i:2;s:3:"500";}}s:22:"attack_throw_animation";s:14:"pose_animation";s:17:"attack_throw_data";a:3:{s:6:"images";a:1:{i:0;s:14:"qbird_head.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"attack_shoot_animation";s:14:"pose_animation";s:17:"attack_shoot_data";a:3:{s:6:"images";a:1:{i:0;s:14:"qbird_head.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"skill_animation";s:14:"pose_animation";s:10:"skill_data";a:3:{s:6:"images";a:1:{i:0;s:14:"qbird_head.gif";}s:6:"sounds";a:1:{i:0;s:24:"qbird_peeka_boo_echo.mp3";}s:5:"times";a:2:{i:0;s:4:"1000";i:1;s:3:"500";}}s:15:"spell_animation";s:14:"pose_animation";s:10:"spell_data";a:3:{s:6:"images";a:1:{i:0;s:14:"qbird_head.gif";}s:6:"sounds";a:1:{i:0;s:24:"qbird_peeka_boo_echo.mp3";}s:5:"times";a:2:{i:0;s:4:"1000";i:1;s:3:"500";}}s:14:"item_animation";s:14:"pose_animation";s:9:"item_data";a:3:{s:6:"images";a:1:{i:0;s:14:"qbird_head.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"overworld_stand_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}s:21:"overworld_move_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}}i:1006;O:11:"PERSONALITY":25:{s:4:"name";s:7:"Crystal";s:14:"base_animation";s:14:"base_animation";s:9:"base_data";a:3:{s:6:"images";a:1:{i:0;s:16:"crystal_boom.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:15:"equip_animation";s:14:"pose_animation";s:10:"equip_data";a:3:{s:6:"images";a:1:{i:0;s:16:"crystal_boom.png";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"flee_animation";s:14:"flee_animation";s:9:"flee_data";a:3:{s:6:"images";a:1:{i:0;s:16:"crystal_boom.png";}s:6:"sounds";a:0:{}s:5:"times";a:1:{i:0;s:1:"0";}}s:13:"hit_animation";s:14:"pose_animation";s:8:"hit_data";a:3:{s:6:"images";a:1:{i:0;s:16:"crystal_boom.png";}s:6:"sounds";a:1:{i:0;s:10:"Earth3.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:13:"die_animation";s:13:"die_animation";s:8:"die_data";a:3:{s:6:"images";a:1:{i:0;s:16:"crystal_boom.png";}s:6:"sounds";a:2:{i:0;s:10:"Earth3.mp3";i:1;s:7:"die.mp3";}s:5:"times";a:3:{i:0;s:3:"500";i:1;s:2:"10";i:2;s:1:"5";}}s:22:"attack_close_animation";s:22:"attack_close_animation";s:17:"attack_close_data";a:3:{s:6:"images";a:3:{i:0;s:16:"crystal_boom.png";i:1;s:21:"crystal_boom_head.gif";i:2;s:16:"crystal_boom.png";}s:6:"sounds";a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}s:5:"times";a:3:{i:0;s:2:"25";i:1;s:3:"500";i:2;s:3:"500";}}s:22:"attack_throw_animation";s:14:"pose_animation";s:17:"attack_throw_data";a:3:{s:6:"images";a:1:{i:0;s:21:"crystal_boom_head.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"attack_shoot_animation";s:14:"pose_animation";s:17:"attack_shoot_data";a:3:{s:6:"images";a:1:{i:0;s:21:"crystal_boom_head.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"skill_animation";s:14:"pose_animation";s:10:"skill_data";a:3:{s:6:"images";a:1:{i:0;s:21:"crystal_boom_head.gif";}s:6:"sounds";a:1:{i:0;s:9:"skill.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:15:"spell_animation";s:14:"pose_animation";s:10:"spell_data";a:3:{s:6:"images";a:1:{i:0;s:21:"crystal_boom_head.gif";}s:6:"sounds";a:1:{i:0;s:10:"cast_2.mp3";}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:14:"item_animation";s:14:"pose_animation";s:9:"item_data";a:3:{s:6:"images";a:1:{i:0;s:21:"crystal_boom_head.gif";}s:6:"sounds";a:0:{}s:5:"times";a:2:{i:0;s:3:"500";i:1;s:3:"500";}}s:22:"overworld_stand_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}s:21:"overworld_move_images";a:4:{s:2:"up";s:0:"";s:4:"down";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";}}}
EOD
);
$GLOBALS["personalities_js"]='[null,
  {\'name\':\'Rolf\',\'base_animation\':\'base_animation\',
    base_data:{
      images:[\'rolf.png\'],
      sounds:[],
      times:[0]
    }
  ,\'equip_animation\':\'pose_animation\',
    equip_data:{
      images:[\'rolf.png\'],
      sounds:[],
      times:[500,500]
    }
  ,\'flee_animation\':\'flee_animation\',
    flee_data:{
      images:[\'rolf.png\'],
      sounds:[],
      times:[0]
    }
  ,\'hit_animation\':\'pose_animation\',
    hit_data:{
      images:[\'rolf.png\'],
      sounds:[\'Earth3.mp3\'],
      times:[500,500]
    }
  ,\'die_animation\':\'die_animation\',
    die_data:{
      images:[\'rolf.png\'],
      sounds:[\'Earth3.mp3\',\'die.mp3\'],
      times:[500,10,5]
    }
  ,\'attack_close_animation\':\'attack_close_animation\',
    attack_close_data:{
      images:[\'rolf.png\',\'rolf_attack.gif\',\'rolf.png\'],
      sounds:[\'\',\'\',\'\'],
      times:[25,500,500]
    }
  ,\'attack_throw_animation\':\'pose_animation\',
    attack_throw_data:{
      images:[\'rolf_attack.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'attack_shoot_animation\':\'pose_animation\',
    attack_shoot_data:{
      images:[\'rolf_attack.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'skill_animation\':\'pose_animation\',
    skill_data:{
      images:[\'rolf_cast.gif\'],
      sounds:[\'skill.mp3\'],
      times:[500,500]
    }
  ,\'spell_animation\':\'pose_animation\',
    spell_data:{
      images:[\'rolf_cast.gif\'],
      sounds:[\'cast_2.mp3\'],
      times:[500,500]
    }
  ,\'item_animation\':\'pose_animation\',
    item_data:{
      images:[\'rolf_cast.gif\'],
      sounds:[],
      times:[500,500]
    },
    overworld_stand_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'},
    overworld_move_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'}
  },
  {\'name\':\'Nei\',\'base_animation\':\'base_animation\',
    base_data:{
      images:[\'nei.png\'],
      sounds:[],
      times:[0]
    }
  ,\'equip_animation\':\'pose_animation\',
    equip_data:{
      images:[\'nei.png\'],
      sounds:[],
      times:[500,500]
    }
  ,\'flee_animation\':\'flee_animation\',
    flee_data:{
      images:[\'nei.png\'],
      sounds:[],
      times:[0]
    }
  ,\'hit_animation\':\'pose_animation\',
    hit_data:{
      images:[\'nei.png\'],
      sounds:[\'Earth3.mp3\'],
      times:[500,500]
    }
  ,\'die_animation\':\'die_animation\',
    die_data:{
      images:[\'nei.png\'],
      sounds:[\'Earth3.mp3\',\'die.mp3\'],
      times:[500,10,5]
    }
  ,\'attack_close_animation\':\'attack_close_animation\',
    attack_close_data:{
      images:[\'nei.png\',\'nei_attack.gif\',\'nei.png\'],
      sounds:[\'\',\'\',\'\'],
      times:[25,500,500]
    }
  ,\'attack_throw_animation\':\'pose_animation\',
    attack_throw_data:{
      images:[\'nei_attack.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'attack_shoot_animation\':\'pose_animation\',
    attack_shoot_data:{
      images:[\'nei_attack.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'skill_animation\':\'pose_animation\',
    skill_data:{
      images:[\'nei_cast.gif\'],
      sounds:[\'skill.mp3\'],
      times:[500,500]
    }
  ,\'spell_animation\':\'pose_animation\',
    spell_data:{
      images:[\'nei_cast.gif\'],
      sounds:[\'cast_2.mp3\'],
      times:[500,500]
    }
  ,\'item_animation\':\'pose_animation\',
    item_data:{
      images:[\'nei_cast.gif\'],
      sounds:[],
      times:[500,500]
    },
    overworld_stand_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'},
    overworld_move_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'}
  },
  {\'name\':\'Alys\',\'base_animation\':\'base_animation\',
    base_data:{
      images:[\'alys.png\'],
      sounds:[],
      times:[0]
    }
  ,\'equip_animation\':\'pose_animation\',
    equip_data:{
      images:[\'alys.png\'],
      sounds:[],
      times:[500,500]
    }
  ,\'flee_animation\':\'flee_animation\',
    flee_data:{
      images:[\'alys.png\'],
      sounds:[],
      times:[0]
    }
  ,\'hit_animation\':\'pose_animation\',
    hit_data:{
      images:[\'alys.png\'],
      sounds:[\'Earth3.mp3\'],
      times:[500,500]
    }
  ,\'die_animation\':\'die_animation\',
    die_data:{
      images:[\'alys.png\'],
      sounds:[\'Earth3.mp3\',\'die.mp3\'],
      times:[500,10,5]
    }
  ,\'attack_close_animation\':\'attack_close_animation\',
    attack_close_data:{
      images:[\'alys.png\',\'alys_attack.gif\',\'alys.png\'],
      sounds:[\'\',\'\',\'\'],
      times:[25,500,500]
    }
  ,\'attack_throw_animation\':\'pose_animation\',
    attack_throw_data:{
      images:[\'alys_attack.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'attack_shoot_animation\':\'pose_animation\',
    attack_shoot_data:{
      images:[\'alys_attack.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'skill_animation\':\'pose_animation\',
    skill_data:{
      images:[\'alys_cast.gif\'],
      sounds:[\'skill.mp3\'],
      times:[500,500]
    }
  ,\'spell_animation\':\'pose_animation\',
    spell_data:{
      images:[\'alys_cast.gif\'],
      sounds:[\'cast_2.mp3\'],
      times:[500,500]
    }
  ,\'item_animation\':\'pose_animation\',
    item_data:{
      images:[\'alys_cast.gif\'],
      sounds:[],
      times:[500,500]
    },
    overworld_stand_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'},
    overworld_move_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'}
  },
  {\'name\':\'Chaz\',\'base_animation\':\'base_animation\',
    base_data:{
      images:[\'chaz.png\'],
      sounds:[],
      times:[0]
    }
  ,\'equip_animation\':\'pose_animation\',
    equip_data:{
      images:[\'chaz.png\'],
      sounds:[],
      times:[500,500]
    }
  ,\'flee_animation\':\'flee_animation\',
    flee_data:{
      images:[\'chaz.png\'],
      sounds:[],
      times:[0]
    }
  ,\'hit_animation\':\'pose_animation\',
    hit_data:{
      images:[\'chaz.png\'],
      sounds:[\'Earth3.mp3\'],
      times:[500,500]
    }
  ,\'die_animation\':\'die_animation\',
    die_data:{
      images:[\'chaz.png\'],
      sounds:[\'Earth3.mp3\',\'die.mp3\'],
      times:[500,10,5]
    }
  ,\'attack_close_animation\':\'attack_close_animation\',
    attack_close_data:{
      images:[\'chaz.png\',\'chaz_attack.gif\',\'chaz.png\'],
      sounds:[\'\',\'\',\'\'],
      times:[25,500,500]
    }
  ,\'attack_throw_animation\':\'pose_animation\',
    attack_throw_data:{
      images:[\'chaz_attack.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'attack_shoot_animation\':\'pose_animation\',
    attack_shoot_data:{
      images:[\'chaz_attack.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'skill_animation\':\'pose_animation\',
    skill_data:{
      images:[\'chaz_cast.gif\'],
      sounds:[\'skill.mp3\'],
      times:[500,500]
    }
  ,\'spell_animation\':\'pose_animation\',
    spell_data:{
      images:[\'chaz_cast.gif\'],
      sounds:[\'cast_2.mp3\'],
      times:[500,500]
    }
  ,\'item_animation\':\'pose_animation\',
    item_data:{
      images:[\'chaz_cast.gif\'],
      sounds:[],
      times:[500,500]
    },
    overworld_stand_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'},
    overworld_move_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'}
  }
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,
  {\'name\':\'Troll\',\'base_animation\':\'base_animation\',
    base_data:{
      images:[\'woodman.png\'],
      sounds:[],
      times:[0]
    }
  ,\'equip_animation\':\'pose_animation\',
    equip_data:{
      images:[\'woodman.png\'],
      sounds:[],
      times:[500,500]
    }
  ,\'flee_animation\':\'flee_animation\',
    flee_data:{
      images:[\'woodman.png\'],
      sounds:[],
      times:[0]
    }
  ,\'hit_animation\':\'pose_animation\',
    hit_data:{
      images:[\'woodman.png\'],
      sounds:[\'Earth3.mp3\'],
      times:[500,500]
    }
  ,\'die_animation\':\'die_animation\',
    die_data:{
      images:[\'woodman.png\'],
      sounds:[\'Earth3.mp3\',\'die.mp3\'],
      times:[500,10,5]
    }
  ,\'attack_close_animation\':\'attack_close_animation\',
    attack_close_data:{
      images:[\'woodman.png\',\'woodman.gif\',\'woodman.png\'],
      sounds:[\'\',\'\',\'\'],
      times:[25,500,500]
    }
  ,\'attack_throw_animation\':\'pose_animation\',
    attack_throw_data:{
      images:[\'woodman.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'attack_shoot_animation\':\'pose_animation\',
    attack_shoot_data:{
      images:[\'woodman.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'skill_animation\':\'pose_animation\',
    skill_data:{
      images:[\'woodman.gif\'],
      sounds:[\'skill.mp3\'],
      times:[500,500]
    }
  ,\'spell_animation\':\'pose_animation\',
    spell_data:{
      images:[\'woodman.gif\'],
      sounds:[\'cast_2.mp3\'],
      times:[500,500]
    }
  ,\'item_animation\':\'pose_animation\',
    item_data:{
      images:[\'woodman.gif\'],
      sounds:[],
      times:[500,500]
    },
    overworld_stand_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'},
    overworld_move_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'}
  },
  {\'name\':\'Goblin\',\'base_animation\':\'base_animation\',
    base_data:{
      images:[\'goblin.png\'],
      sounds:[],
      times:[0]
    }
  ,\'equip_animation\':\'pose_animation\',
    equip_data:{
      images:[\'goblin.png\'],
      sounds:[],
      times:[500,500]
    }
  ,\'flee_animation\':\'flee_animation\',
    flee_data:{
      images:[\'goblin.png\'],
      sounds:[],
      times:[0]
    }
  ,\'hit_animation\':\'pose_animation\',
    hit_data:{
      images:[\'goblin.png\'],
      sounds:[\'Earth3.mp3\'],
      times:[500,500]
    }
  ,\'die_animation\':\'die_animation\',
    die_data:{
      images:[\'goblin.png\'],
      sounds:[\'Earth3.mp3\',\'die.mp3\'],
      times:[500,10,5]
    }
  ,\'attack_close_animation\':\'attack_close_animation\',
    attack_close_data:{
      images:[\'goblin.png\',\'goblin.gif\',\'goblin.png\'],
      sounds:[\'\',\'\',\'\'],
      times:[25,500,500]
    }
  ,\'attack_throw_animation\':\'pose_animation\',
    attack_throw_data:{
      images:[\'goblin.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'attack_shoot_animation\':\'pose_animation\',
    attack_shoot_data:{
      images:[\'goblin.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'skill_animation\':\'pose_animation\',
    skill_data:{
      images:[\'goblin.gif\'],
      sounds:[\'skill.mp3\'],
      times:[500,500]
    }
  ,\'spell_animation\':\'pose_animation\',
    spell_data:{
      images:[\'goblin.gif\'],
      sounds:[\'cast_2.mp3\'],
      times:[500,500]
    }
  ,\'item_animation\':\'pose_animation\',
    item_data:{
      images:[\'goblin.gif\'],
      sounds:[],
      times:[500,500]
    },
    overworld_stand_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'},
    overworld_move_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'}
  },
  {\'name\':\'Gremlin\',\'base_animation\':\'base_animation\',
    base_data:{
      images:[\'gremlin.png\'],
      sounds:[],
      times:[0]
    }
  ,\'equip_animation\':\'pose_animation\',
    equip_data:{
      images:[\'gremlin.png\'],
      sounds:[],
      times:[500,500]
    }
  ,\'flee_animation\':\'flee_animation\',
    flee_data:{
      images:[\'gremlin.png\'],
      sounds:[],
      times:[0]
    }
  ,\'hit_animation\':\'pose_animation\',
    hit_data:{
      images:[\'gremlin.png\'],
      sounds:[\'Earth3.mp3\'],
      times:[500,500]
    }
  ,\'die_animation\':\'die_animation\',
    die_data:{
      images:[\'gremlin.png\'],
      sounds:[\'Earth3.mp3\',\'die.mp3\'],
      times:[500,10,5]
    }
  ,\'attack_close_animation\':\'attack_close_animation\',
    attack_close_data:{
      images:[\'gremlin.png\',\'gremlin.gif\',\'gremlin.png\'],
      sounds:[\'\',\'\',\'\'],
      times:[25,500,500]
    }
  ,\'attack_throw_animation\':\'pose_animation\',
    attack_throw_data:{
      images:[\'gremlin.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'attack_shoot_animation\':\'pose_animation\',
    attack_shoot_data:{
      images:[\'gremlin.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'skill_animation\':\'pose_animation\',
    skill_data:{
      images:[\'gremlin.gif\'],
      sounds:[\'skill.mp3\'],
      times:[500,500]
    }
  ,\'spell_animation\':\'pose_animation\',
    spell_data:{
      images:[\'gremlin.gif\'],
      sounds:[\'cast_2.mp3\'],
      times:[500,500]
    }
  ,\'item_animation\':\'pose_animation\',
    item_data:{
      images:[\'gremlin.gif\'],
      sounds:[],
      times:[500,500]
    },
    overworld_stand_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'},
    overworld_move_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'}
  },
  {\'name\':\'Hippo\',\'base_animation\':\'base_animation\',
    base_data:{
      images:[\'hungry_hippo.png\'],
      sounds:[],
      times:[0]
    }
  ,\'equip_animation\':\'pose_animation\',
    equip_data:{
      images:[\'hungry_hippo.png\'],
      sounds:[],
      times:[500,500]
    }
  ,\'flee_animation\':\'flee_animation\',
    flee_data:{
      images:[\'hungry_hippo.png\'],
      sounds:[],
      times:[0]
    }
  ,\'hit_animation\':\'pose_animation\',
    hit_data:{
      images:[\'hungry_hippo.png\'],
      sounds:[\'Earth3.mp3\'],
      times:[500,500]
    }
  ,\'die_animation\':\'die_animation\',
    die_data:{
      images:[\'hungry_hippo.png\'],
      sounds:[\'Earth3.mp3\',\'die.mp3\'],
      times:[500,10,5]
    }
  ,\'attack_close_animation\':\'attack_close_animation\',
    attack_close_data:{
      images:[\'hungry_hippo.png\',\'hungry_hippo.gif\',\'hungry_hippo.png\'],
      sounds:[\'\',\'\',\'\'],
      times:[25,500,500]
    }
  ,\'attack_throw_animation\':\'pose_animation\',
    attack_throw_data:{
      images:[\'hungry_hippo.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'attack_shoot_animation\':\'pose_animation\',
    attack_shoot_data:{
      images:[\'hungry_hippo.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'skill_animation\':\'pose_animation\',
    skill_data:{
      images:[\'hungry_hippo.gif\'],
      sounds:[\'skill.mp3\'],
      times:[500,500]
    }
  ,\'spell_animation\':\'pose_animation\',
    spell_data:{
      images:[\'hungry_hippo.gif\'],
      sounds:[\'cast_2.mp3\'],
      times:[500,500]
    }
  ,\'item_animation\':\'pose_animation\',
    item_data:{
      images:[\'hungry_hippo.gif\'],
      sounds:[],
      times:[500,500]
    },
    overworld_stand_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'},
    overworld_move_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'}
  },
  {\'name\':\'Jordie\',\'base_animation\':\'base_animation\',
    base_data:{
      images:[\'jordie.png\'],
      sounds:[],
      times:[0]
    }
  ,\'equip_animation\':\'pose_animation\',
    equip_data:{
      images:[\'jordie.png\'],
      sounds:[],
      times:[500,500]
    }
  ,\'flee_animation\':\'flee_animation\',
    flee_data:{
      images:[\'jordie.png\'],
      sounds:[],
      times:[0]
    }
  ,\'hit_animation\':\'pose_animation\',
    hit_data:{
      images:[\'jordie.png\'],
      sounds:[\'jordie_squeak.mp3\'],
      times:[500,500]
    }
  ,\'die_animation\':\'die_animation\',
    die_data:{
      images:[\'jordie_die.gif\'],
      sounds:[\'Earth3.mp3\',\'jordie_shreak.mp3\'],
      times:[700,500,5]
    }
  ,\'attack_close_animation\':\'attack_close_animation\',
    attack_close_data:{
      images:[\'jordie.png\',\'jordie_ani.gif\',\'jordie.png\'],
      sounds:[\'\',\'jordie_hey.mp3\',\'\'],
      times:[25,500,500]
    }
  ,\'attack_throw_animation\':\'pose_animation\',
    attack_throw_data:{
      images:[\'jordie_ani.gif\'],
      sounds:[\'jordie_hey.mp3\'],
      times:[500,500]
    }
  ,\'attack_shoot_animation\':\'pose_animation\',
    attack_shoot_data:{
      images:[\'jordie_ani.gif\'],
      sounds:[\'jordie_hey.mp3\'],
      times:[500,500]
    }
  ,\'skill_animation\':\'pose_animation\',
    skill_data:{
      images:[\'jordie.png\'],
      sounds:[\'skill.mp3\'],
      times:[500,500]
    }
  ,\'spell_animation\':\'pose_animation\',
    spell_data:{
      images:[\'jordie.png\'],
      sounds:[\'cast_2.mp3\'],
      times:[500,500]
    }
  ,\'item_animation\':\'pose_animation\',
    item_data:{
      images:[\'jordie.png\'],
      sounds:[],
      times:[500,500]
    },
    overworld_stand_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'},
    overworld_move_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'}
  },
  {\'name\':\'Q Bird\',\'base_animation\':\'base_animation\',
    base_data:{
      images:[\'qbird.png\'],
      sounds:[],
      times:[0]
    }
  ,\'equip_animation\':\'pose_animation\',
    equip_data:{
      images:[\'qbird.png\'],
      sounds:[],
      times:[500,500]
    }
  ,\'flee_animation\':\'flee_animation\',
    flee_data:{
      images:[\'qbird.png\'],
      sounds:[],
      times:[0]
    }
  ,\'hit_animation\':\'pose_animation\',
    hit_data:{
      images:[\'qbird.png\'],
      sounds:[\'Earth3.mp3\'],
      times:[500,500]
    }
  ,\'die_animation\':\'die_animation\',
    die_data:{
      images:[\'qbird.png\'],
      sounds:[\'Earth3.mp3\',\'die.mp3\'],
      times:[500,10,5]
    }
  ,\'attack_close_animation\':\'attack_close_animation\',
    attack_close_data:{
      images:[\'qbird.png\',\'qbird_head.gif\',\'qbird.png\'],
      sounds:[\'\',\'\',\'\'],
      times:[25,500,500]
    }
  ,\'attack_throw_animation\':\'pose_animation\',
    attack_throw_data:{
      images:[\'qbird_head.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'attack_shoot_animation\':\'pose_animation\',
    attack_shoot_data:{
      images:[\'qbird_head.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'skill_animation\':\'pose_animation\',
    skill_data:{
      images:[\'qbird_head.gif\'],
      sounds:[\'qbird_peeka_boo_echo.mp3\'],
      times:[1000,500]
    }
  ,\'spell_animation\':\'pose_animation\',
    spell_data:{
      images:[\'qbird_head.gif\'],
      sounds:[\'qbird_peeka_boo_echo.mp3\'],
      times:[1000,500]
    }
  ,\'item_animation\':\'pose_animation\',
    item_data:{
      images:[\'qbird_head.gif\'],
      sounds:[],
      times:[500,500]
    },
    overworld_stand_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'},
    overworld_move_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'}
  },
  {\'name\':\'Crystal\',\'base_animation\':\'base_animation\',
    base_data:{
      images:[\'crystal_boom.png\'],
      sounds:[],
      times:[0]
    }
  ,\'equip_animation\':\'pose_animation\',
    equip_data:{
      images:[\'crystal_boom.png\'],
      sounds:[],
      times:[500,500]
    }
  ,\'flee_animation\':\'flee_animation\',
    flee_data:{
      images:[\'crystal_boom.png\'],
      sounds:[],
      times:[0]
    }
  ,\'hit_animation\':\'pose_animation\',
    hit_data:{
      images:[\'crystal_boom.png\'],
      sounds:[\'Earth3.mp3\'],
      times:[500,500]
    }
  ,\'die_animation\':\'die_animation\',
    die_data:{
      images:[\'crystal_boom.png\'],
      sounds:[\'Earth3.mp3\',\'die.mp3\'],
      times:[500,10,5]
    }
  ,\'attack_close_animation\':\'attack_close_animation\',
    attack_close_data:{
      images:[\'crystal_boom.png\',\'crystal_boom_head.gif\',\'crystal_boom.png\'],
      sounds:[\'\',\'\',\'\'],
      times:[25,500,500]
    }
  ,\'attack_throw_animation\':\'pose_animation\',
    attack_throw_data:{
      images:[\'crystal_boom_head.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'attack_shoot_animation\':\'pose_animation\',
    attack_shoot_data:{
      images:[\'crystal_boom_head.gif\'],
      sounds:[],
      times:[500,500]
    }
  ,\'skill_animation\':\'pose_animation\',
    skill_data:{
      images:[\'crystal_boom_head.gif\'],
      sounds:[\'skill.mp3\'],
      times:[500,500]
    }
  ,\'spell_animation\':\'pose_animation\',
    spell_data:{
      images:[\'crystal_boom_head.gif\'],
      sounds:[\'cast_2.mp3\'],
      times:[500,500]
    }
  ,\'item_animation\':\'pose_animation\',
    item_data:{
      images:[\'crystal_boom_head.gif\'],
      sounds:[],
      times:[500,500]
    },
    overworld_stand_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'},
    overworld_move_images:{\'up\':\'\',\'down\':\'\',\'left\':\'\',\'right\':\'\'}
  }
]'; ?>